# Generated by Django 4.2.2 on 2023-06-27 04:45

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(default=leads.models.get_nano_id, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
