# Generated by Django 4.2.2 on 2023-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convert_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
