# Generated by Django 4.2.2 on 2023-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-modified_at',)},
        ),
    ]
