# Generated by Django 4.2.2 on 2023-07-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='convert_to_client',
        ),
    ]
