# Generated by Django 4.2.2 on 2023-07-05 13:49

import CRM.nano_id_function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(default=CRM.nano_id_function.get_nano_id, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_leads', models.IntegerField()),
                ('max_client', models.IntegerField()),
            ],
        ),
    ]
